/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuCategoryRouteImport } from './routes/menu.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuCategoryRoute = MenuCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => MenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu': typeof MenuRouteWithChildren
  '/menu/$category': typeof MenuCategoryRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu/$category': typeof MenuCategoryRoute
  '/menu': typeof MenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu': typeof MenuRouteWithChildren
  '/menu/$category': typeof MenuCategoryRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/menu' | '/menu/$category' | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/menu/$category' | '/menu'
  id: '__root__' | '/' | '/menu' | '/menu/$category' | '/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuRoute: typeof MenuRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/$category': {
      id: '/menu/$category'
      path: '/$category'
      fullPath: '/menu/$category'
      preLoaderRoute: typeof MenuCategoryRouteImport
      parentRoute: typeof MenuRoute
    }
  }
}

interface MenuRouteChildren {
  MenuCategoryRoute: typeof MenuCategoryRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuCategoryRoute: MenuCategoryRoute,
  MenuIndexRoute: MenuIndexRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
